services:

  pg:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=geekhub
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=geekhub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: postgresql-spring-geekhub
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-spring-geekhub
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/geekhub
      SPRING_DATASOURCE_USERNAME: geekhub
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - pg
    networks:
      - backend
networks:
  backend:

volumes:
  pgdata:
  pgadmin-data: